### ISSUE TITLE
Failure in build time test

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/paleomix#13] opened 2017-11-16 11:58 UTC
Hi,
I tried to upgrade the Debian package of paleomix to the latest release 1.2.12 and noticed that there is a build time issue.  I skipped the test test_requirementobj__version__command_not_executable and in the comment of the according [patch](https://anonscm.debian.org/cgit/debian-med/paleomix.git/tree/debian/patches/exclude_failing_test.patch) I droped the error that results when keeping the test.
Am I missing something or is this test just wrong?
Kind regards, Andreas.

**Comment by MikkelSchubert** [comment] 2017-11-20 18:23
Hi Andreas,
Thank you very much for the report.

I'm pushing a fix for this test.
The problem is that it relies on the existence of the 'README.md' file, which used to exist in both the root and the tests/ directory, until one of the two files was renamed. Depending on how you ran the tests, it would use one or the other, so the patch simply makes sure that the naming is consistent.

Cheers

**Closed** 2017-11-20 18:24 UTC
